# Codecov configuration for Ask Dr Chaffee

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - backend/scripts/
    carryforward: false
  
  windows:
    carryforward: false

ignore:
  - "tests/"
  - "**/__pycache__/"
  - "**/venv/"
  - "**/.venv/"
  - "frontend/"
  - "**/*.md"
  - "setup.py"
  - "conftest.py"

github_checks:
  annotations: true
